name: Create release

on:
  push:
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.13'
          cache: true
      - name: Check lock file
        run: pdm lock --check
      - name: Create build artifact
        run: pdm build --no-sdist
#      - name: Publish package distributions to PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/confidence-*.whl
